#############################
# Dahua Configuration V1.0
#############################
CAMERA_NAME="CCTV SUHU"
CAMERA_IP="IP Camera"
CAMERA_PORT="80"
CAMERA_USER="admin"
CAMERA_PASS="admin"
TIMEOUT=10
RETRY=3
IMAGE_QUALITY_MIN_SIZE=10240
RETENTION_DAYS=90
